class Dashboard::LandingPageSettingsController < Dashboard::ResourceController
  def landing_page_setting_params
  	params.require(:landing_page_setting).permit(
            :id,
            :photo_1,
            :photo_2,
            :photo_3,
            :photo_4,
            :video_1,
            :video_2,
            :video_3,
            :video_4,
            :call_to_action_background,
            :header_message,
            :subheader_message,
            :header_description_message,
            :endorsement_header,
            :endorsement_description,
            :testimonial_header,
            :testimonial_description,
            :features_header,
            :features_description,
            :owners_header,
            :owners_description,
            :contact_messages_header,
            :contact_messages_description,
            :plans_header,
            :plans_description
            )
  end
end
